name: Deploy to HuggingFace Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Push to HuggingFace Space
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git clone https://huggingface.co/spaces/aputze/Deep_research hf_space
          rsync -av --delete --exclude=".git" . hf_space/
          cd hf_space
          git add .
          git commit -m "Auto deploy from GitHub" || echo "Nothing to commit"
          git push https://aputze:$HF_TOKEN@huggingface.co/spaces/aputze/Deep_research
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
